#include "guile_opencl.h"

void cl_check_value(cl_int value, const char* subr) {
    switch(value) {
    case CL_SUCCESS: return;
#define GENERATE_CASE(name) case name: scm_misc_error(subr, #name, SCM_EOL); return
        GENERATE_CASE(CL_DEVICE_NOT_FOUND);
        GENERATE_CASE(CL_DEVICE_NOT_AVAILABLE);
        GENERATE_CASE(CL_COMPILER_NOT_AVAILABLE);
        GENERATE_CASE(CL_MEM_OBJECT_ALLOCATION_FAILURE);
        GENERATE_CASE(CL_OUT_OF_RESOURCES);
        GENERATE_CASE(CL_OUT_OF_HOST_MEMORY);
        GENERATE_CASE(CL_PROFILING_INFO_NOT_AVAILABLE);
        GENERATE_CASE(CL_MEM_COPY_OVERLAP);
        GENERATE_CASE(CL_IMAGE_FORMAT_MISMATCH);
        GENERATE_CASE(CL_IMAGE_FORMAT_NOT_SUPPORTED);
        GENERATE_CASE(CL_BUILD_PROGRAM_FAILURE);
        GENERATE_CASE(CL_MAP_FAILURE);
        GENERATE_CASE(CL_MISALIGNED_SUB_BUFFER_OFFSET);
        GENERATE_CASE(CL_EXEC_STATUS_ERROR_FOR_EVENTS_IN_WAIT_LIST);
        GENERATE_CASE(CL_INVALID_VALUE);
        GENERATE_CASE(CL_INVALID_DEVICE_TYPE);
        GENERATE_CASE(CL_INVALID_PLATFORM);
        GENERATE_CASE(CL_INVALID_DEVICE);
        GENERATE_CASE(CL_INVALID_CONTEXT);
        GENERATE_CASE(CL_INVALID_QUEUE_PROPERTIES);
        GENERATE_CASE(CL_INVALID_COMMAND_QUEUE);
        GENERATE_CASE(CL_INVALID_HOST_PTR);
        GENERATE_CASE(CL_INVALID_MEM_OBJECT);
        GENERATE_CASE(CL_INVALID_IMAGE_FORMAT_DESCRIPTOR);
        GENERATE_CASE(CL_INVALID_IMAGE_SIZE);
        GENERATE_CASE(CL_INVALID_SAMPLER);
        GENERATE_CASE(CL_INVALID_BINARY);
        GENERATE_CASE(CL_INVALID_BUILD_OPTIONS);
        GENERATE_CASE(CL_INVALID_PROGRAM);
        GENERATE_CASE(CL_INVALID_PROGRAM_EXECUTABLE);
        GENERATE_CASE(CL_INVALID_KERNEL_NAME);
        GENERATE_CASE(CL_INVALID_KERNEL_DEFINITION);
        GENERATE_CASE(CL_INVALID_KERNEL);
        GENERATE_CASE(CL_INVALID_ARG_INDEX);
        GENERATE_CASE(CL_INVALID_ARG_VALUE);
        GENERATE_CASE(CL_INVALID_ARG_SIZE);
        GENERATE_CASE(CL_INVALID_KERNEL_ARGS);
        GENERATE_CASE(CL_INVALID_WORK_DIMENSION);
        GENERATE_CASE(CL_INVALID_WORK_GROUP_SIZE);
        GENERATE_CASE(CL_INVALID_WORK_ITEM_SIZE);
        GENERATE_CASE(CL_INVALID_GLOBAL_OFFSET);
        GENERATE_CASE(CL_INVALID_EVENT_WAIT_LIST);
        GENERATE_CASE(CL_INVALID_EVENT);
        GENERATE_CASE(CL_INVALID_OPERATION);
        GENERATE_CASE(CL_INVALID_GL_OBJECT);
        GENERATE_CASE(CL_INVALID_BUFFER_SIZE);
        GENERATE_CASE(CL_INVALID_MIP_LEVEL);
        GENERATE_CASE(CL_INVALID_GLOBAL_WORK_SIZE);
        GENERATE_CASE(CL_INVALID_PROPERTY);
#undef GENERATE_CASE
    default:
        scm_misc_error(subr, "unknown error", SCM_EOL);
    }
}

void cl_callback(const char *errinfo,
                 const void *private_info,
                 size_t cb,
                 void *user_data) {
    if(NULL == user_data) {
        scm_misc_error("cl_callback", errinfo, SCM_EOL);
    } else {
        scm_misc_error((char *)user_data, errinfo, SCM_EOL);
    }
}
